tools:

  - name: add_two_numbers
    description: Add two numbers together
    parameters:
      type: object
      required: [ a, b ]
      properties:
        a:
          type: integer
          description: The first number
        b:
          type: integer
          description: The second number

  - name: subtract_two_numbers
    description: Subtract two numbers
    parameters:
      type: object
      required: [ a, b ]
      properties:
        a:
          type: integer
          description: The first number
        b:
          type: integer
          description: The second number