tools:
  - name : get_info
    description: Get the IP address of a given domain
    parameters:
      type: object
      required: [ domain ]
      properties:
        domain:
          type: string
          description: The target domain name
  
  - name: scan_network
    description: Scan a network for open ports
    parameters:
      type: object
      required: [ target ]
      properties:
        target:
          type: string
          description: The IP address to scan for open ports