tools:
  - name : get_info
    description: Get the IP address of a given domain
    parameters:
      type: object
      required: [ domain ]
      properties:
        domain:
          type: string
          description: The target domain name
  
  - name: scan_network
    description: Scan a network for open ports
    parameters:
      type: object
      required: [ ip_address ]
      properties:
        ip_address:
          type: string
          description: The IP address to scan for open ports

  - name: check_vulnerability
    description: Check for vulnerabilities in a given domain
    parameters:
      type: object
      required: [ domain ]
      properties:
        domain:
          type: string
          description: The domain to check for vulnerabilities
  
  - name: sql_injection
    description: Check for SQL injection vulnerabilities in a given URL
    parameters:
      type: object
      required: [ url ]
      properties:
        url:
          type: string
          description: The URL to check for SQL injection vulnerabilities
  
  - name: hash_text
    description: Compute a hash of input text
    parameters:
      type: object
      required: [ text ]
      properties:
        text:
          type: string
          description: The text to hash
        algorithm:
          type: string
          description: Hash algorithm to use
          enum: [ sha256, md5 ]