tools:
  - name: add_two_numbers
    description: Add two numbers together
    parameters:
      type: object
      required: [ a, b ]
      properties:
        a:
          type: integer
          description: The first number
        b:
          type: integer
          description: The second number

  - name: subtract_two_numbers
    description: Subtract two numbers
    parameters:
      type: object
      required: [ a, b ]
      properties:
        a:
          type: integer
          description: The first number
        b:
          type: integer
          description: The second number
  
  - name : get_info
    description: Get the IP address of a given domain
    parameters:
      type: object
      required: [ domain ]
      properties:
        domain:
          type: string
          description: The domain name to get the IP address for
  