tools:
  - name: get_current_weather
    description: Get the current weather for a specified city
    parameters:
      type: object
      properties:
        city:
          type: string
          description: The city to get weather information for
      required:
        - city

  - name: add_two_numbers
    description: Add two numbers together
    parameters:
      type: object
      required: [ a, b ]
      properties:
        a:
          type: integer
          description: The first number
        b:
          type: integer
          description: The second number

  - name: subtract_two_numbers
    description: Subtract two numbers
    parameters:
      type: object
      required: [ a, b ]
      properties:
        a:
          type: integer
          description: The first number
        b:
          type: integer
          description: The second number

  - name: get_current_time
    description: Get the current time
    parameters:
      type: object
      properties:
        timezone:
          type: string
          description: The timezone to get the time in
      required:
        - timezone