# This workflow will run tests and generate coverage reports for the Streamlit Ollama Chat application

name: Python Tests

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - name : Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov pytest-asyncio pytest-mock pytest-xdist
        
    - name: Run unit tests
      run: |
        python run_tests.py --unit --coverage
        
    - name: Run integration tests
      run: |
        python run_tests.py --integration
        
    - name: Generate coverage report
      run: |
        python -m pytest tests/unit/ tests/integration/ --cov --cov-branch --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ifrazie/krytos-llm